#%RAML 1.0 ResourceType
usage: this resourceTypes can be used for any collection.
get:

    description: This method returns <<resourcePathName>> 
    responses: 
      200:
        body: 
          application/json:
            type: <<getResponsetype>>
            example: | 
              <<examplereference1>>



